---

# Copyright 2023 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
    - "default.yml"

- name: Update NSS to the latest version
  ansible.builtin.package:
    name: nss
    state: latest

- name: Install Python and supporting packages
  ansible.builtin.package:
    lock_timeout: 180
    name: "{{ __pyver_item }}"
    update_cache: yes
    state: present
  loop:
    - python3
    - python2
  loop_control:
    loop_var: __pyver_item
      
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  notify: restart host

- name: Install base FreeIPA server packages
  ansible.builtin.package:
    name: "{{ ipaserver_packages }}"
    state: present

- name: Set up DNS and networking
  when: ipaserver_setup_dns
  block:
    - name: Configure RHEL systems
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Set cloud-init to preserve hostname (RHEL)
          ansible.builtin.lineinfile:
            path: /etc/cloud/cloud.cfg
            regex: "^(#)?preserve_hostname"
            line: "preserve_hostname: 1"
            state: present
          notify: restart host

        - name: Check for existence of /etc/NetworkManager/conf.d
          ansible.builtin.stat: path=/etc/NetworkManager/conf.d
          register: st
          
        - name: Set /etc/NetworkManager/conf.d/disable-resolve.conf-managing.conf (RHEL)
          ansible.builtin.copy:
            dest: /etc/NetworkManager/conf.d/disable-resolve.conf-managing.conf
            content: |
              # Generated by Ansible
              [main]
              dns=none
          when: st.stat.exists        
          notify: restart host

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
